apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  {{- if .Values.namespace.labels }}
  labels:
  {{- with .Values.namespace.labels }}
  {{ toYaml . | indent 4 }}
  {{- end }}
  {{- end }}
