app:
  syncWave: "-20"
  server: https://kubernetes.default.svc

  domain: app2.px.igniteme.dev
  repoName: react-REPO_NAME
  imageList: frontend=gcr.io/GCP_PROJECT_ID/prod-app2/frontend
  lifecycle: prod

  frontend:
    enabled: true
  backend:
    enabled: false
