---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: walker-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    tier: platform
    deployment: kustomize
spec:
  project: walker
  source:
    repoURL: https://github.com/MavenWave-DevOps/REPO_NAME.git
    targetRevision: HEAD
    path: kustomize/tenants/walker/cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: walker
