apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- tenant-apps.yaml
- tenant-namespaces.yaml
- tenant-projects.yaml

patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: ApplicationSet
  patch: |-
    - op: replace
      path: /spec/generators/0/git/revision
      value: HEAD
    - op: replace
      path: /spec/template/spec/source/targetRevision
      value: HEAD
