---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viewer-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: viewer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
