---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewer
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"