---
namespace:
  labels: {}

external-secrets:
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: external-secrets@GCP_PROJECT_ID.iam.gserviceaccount.com

  resources:
    requests:
      cpu: ".01"
      memory: 32Mi
    limits:
      cpu: ".05"
      memory: 64Mi

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000


  certController:
    resources:
      requests:
        cpu: ".01"
        memory: 64Mi
      limits:
        cpu: ".05"
        memory: 128Mi

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000


  webhook:
    resources:
      requests:
        cpu: ".001"
        memory: 32Mi
      limits:
        cpu: ".01"
        memory: 64Mi

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000


